---
title: "MicData"
author: "Yolanda Yang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MicData}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## choose the mic you want!

Now with this package, you can try to get all the mic models by calling ```gModel()```.
This will give you a list of models available. Inside the ```gModel()``` function, a helper function ```getMember()``` is called to get a specific member of each vector in a list.

## Get a description!

After you have make your decision, use the model name that you get from ```gModel()``` as the input of ```gDescription()``` to get a general description of that mic!

## Please tell me the technical data!

You decided that you like this mic very much according to its description. Why not have a look at its technical data before you buy it? Again, use the model name that you get from ```gModel()``` as the input of ```gMicData()``` to get the technical data of your favorite mic! To me, the KU100 binaural mic seems to be very interesting! ```gMicData("ku100")``` would give me what I want!

## Reflections

Everything work nicely until I got to the point to do a ```devtools::check()```. Unfortunately, I can not get ```devtools::check()``` completed because the url I used is a secure site that begins with ```https://``` instead of ```http://``` and ```readLines()``` cannot access the server easily when doing such a check. ```getURL()``` in 'RCurl" package seems to be the solution, but in that case all the html syntax and useful data will clump together into several character strings instead of separating into lines. I have to think of another way to extract the data, which I don't have any idea at the moment.. Function ```htmlTreeParse()``` in "XML" package also seems to be useful to parse the html syntax. However, I was stuck on how to deal with the parsed object after applying ```htmlTreeParse()``` as I am not familiar with html format at all. Any thoughts would be appreciated!
